export const date = [
  {
    id: 0,
    imgUrl: "/logos/ajax.png",
    label: "Ajax",
    matched: false,
  },
  {
    id: 1,
    imgUrl: "/logos/bem.png",
    label: "Bem",
    matched: false,
  },
  {
    id: 2,
    imgUrl: "/logos/bootstrap.png",
    label: "Bootstrap",
    matched: false,
  },
  {
    id: 3,
    imgUrl: "/logos/css.png",
    label: "Css",
    matched: false,
  },
  {
    id: 4,
    imgUrl: "/logos/git.png",
    label: "Git",
    matched: false,
  },
  {
    id: 5,
    imgUrl: "/logos/html.png",
    label: "HTML",
    matched: false,
  },
  {
    id: 6,
    imgUrl: "/logos/jest.png",
    label: "Jest",
    matched: false,
  },
  {
    id: 7,
    imgUrl: "/logos/js.png",
    label: "JS",
    matched: false,
  },
  {
    id: 8,
    imgUrl: "/logos/mui.png",
    label: "Mui",
    matched: false,
  },
  {
    id: 9,
    imgUrl: "/logos/oop.png",
    label: "OOP",
    matched: false,
  },
  {
    id: 10,
    imgUrl: "/logos/react.png",
    label: "React",
    matched: false,
  },
  {
    id: 11,
    imgUrl: "/logos/redux.png",
    label: "Redux",
    matched: false,
  },
  {
    id: 12,
    imgUrl: "/logos/rest.png",
    label: "Rest",
    matched: false,
  },
  {
    id: 13,
    imgUrl: "/logos/sass.png",
    label: "Sass",
    matched: false,
  },
  {
    id: 14,
    imgUrl: "/logos/ts.png",
    label: "TS",
    matched: false,
  },
];
